language: node_js
node_js:
- 14.3.0
deploy:
  provider: gae
  keyfile: client-secret.json
  project: devbook-cs3219
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
