version: "3"
services:
  devbook-server:
    build:
      context: .
    container_name: devbook-server-container
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
